import fs from 'fs';

const realPlayers = [
    { name: "Virat Kohli", role: "BAT", nat: "IND", category: "STAR" },
    { name: "Rohit Sharma", role: "BAT", nat: "IND", category: "STAR" },
    { name: "Jasprit Bumrah", role: "BOWL", nat: "IND", category: "STAR" },
    { name: "Hardik Pandya", role: "AR", nat: "IND", category: "STAR" },
    { name: "Suryakumar Yadav", role: "BAT", nat: "IND", category: "STAR" },
    { name: "MS Dhoni", role: "WK", nat: "IND", category: "CONSISTENT" },
    { name: "Ravindra Jadeja", role: "AR", nat: "IND", category: "CONSISTENT" },
    { name: "Rishabh Pant", role: "WK", nat: "IND", category: "VOLATILE" },
    { name: "Shubman Gill", role: "BAT", nat: "IND", category: "CONSISTENT" },
    { name: "KL Rahul", role: "WK", nat: "IND", category: "CONSISTENT" },
    { name: "Shreyas Iyer", role: "BAT", nat: "IND", category: "CONSISTENT" },
    { name: "Ishan Kishan", role: "WK", nat: "IND", category: "VOLATILE" },
    { name: "Sanju Samson", role: "WK", nat: "IND", category: "VOLATILE" },
    { name: "Yuzvendra Chahal", role: "BOWL", nat: "IND", category: "STAR" },
    { name: "Mohammed Shami", role: "BOWL", nat: "IND", category: "STAR" },
    { name: "Mohammed Siraj", role: "BOWL", nat: "IND", category: "STAR" },
    { name: "Arshdeep Singh", role: "BOWL", nat: "IND", category: "CONSISTENT" },
    { name: "Kuldeep Yadav", role: "BOWL", nat: "IND", category: "STAR" },
    { name: "Axar Patel", role: "AR", nat: "IND", category: "CONSISTENT" },
    { name: "Ruturaj Gaikwad", role: "BAT", nat: "IND", category: "CONSISTENT" },
    { name: "Yashasvi Jaiswal", role: "BAT", nat: "IND", category: "VOLATILE" },
    { name: "Bhuvneshwar Kumar", role: "BOWL", nat: "IND", category: "CONSISTENT" },
    { name: "Deepak Chahar", role: "BOWL", nat: "IND", category: "CONSISTENT" },
    { name: "Shardul Thakur", role: "AR", nat: "IND", category: "VOLATILE" },
    { name: "Washington Sundar", role: "AR", nat: "IND", category: "CONSISTENT" },
    { name: "Rinku Singh", role: "BAT", nat: "IND", category: "VOLATILE" },
    { name: "Tilak Varma", role: "BAT", nat: "IND", category: "CONSISTENT" },
    { name: "Umran Malik", role: "BOWL", nat: "IND", category: "VOLATILE" },
    { name: "Mukesh Kumar", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Avesh Khan", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Prithvi Shaw", role: "BAT", nat: "IND", category: "VOLATILE" },
    { name: "Nitish Rana", role: "AR", nat: "IND", category: "CONSISTENT" },
    { name: "Venkatesh Iyer", role: "AR", nat: "IND", category: "VOLATILE" },
    { name: "Rahul Tripathi", role: "BAT", nat: "IND", category: "VOLATILE" },
    { name: "Mayank Agarwal", role: "BAT", nat: "IND", category: "CONSISTENT" },
    { name: "Shivam Dube", role: "AR", nat: "IND", category: "VOLATILE" },
    { name: "Harshal Patel", role: "BOWL", nat: "IND", category: "CONSISTENT" },
    { name: "Ravi Bishnoi", role: "BOWL", nat: "IND", category: "CONSISTENT" },
    { name: "Umesh Yadav", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Ajinkya Rahane", role: "BAT", nat: "IND", category: "CONSISTENT" },
    { name: "Shikhar Dhawan", role: "BAT", nat: "IND", category: "CONSISTENT" },
    { name: "Dinesh Karthik", role: "WK", nat: "IND", category: "VOLATILE" },
    { name: "Krunal Pandya", role: "AR", nat: "IND", category: "CONSISTENT" },
    { name: "Deepak Hooda", role: "AR", nat: "IND", category: "WEAK" },
    { name: "Rahul Chahar", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Varun Chakaravarthy", role: "BOWL", nat: "IND", category: "STAR" },
    { name: "Ravichandran Ashwin", role: "AR", nat: "IND", category: "CONSISTENT" },
    { name: "T Natarajan", role: "BOWL", nat: "IND", category: "CONSISTENT" },
    { name: "Khaleel Ahmed", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Navdeep Saini", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Sandeep Sharma", role: "BOWL", nat: "IND", category: "CONSISTENT" },
    { name: "Mohit Sharma", role: "BOWL", nat: "IND", category: "CONSISTENT" },
    { name: "Ishant Sharma", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Piyush Chawla", role: "BOWL", nat: "IND", category: "CONSISTENT" },
    { name: "Amit Mishra", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Jaydev Unadkat", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Manish Pandey", role: "BAT", nat: "IND", category: "WEAK" },
    { name: "Vijay Shankar", role: "AR", nat: "IND", category: "WEAK" },
    { name: "Mandeep Singh", role: "BAT", nat: "IND", category: "WEAK" },
    { name: "Rahul Tewatia", role: "AR", nat: "IND", category: "VOLATILE" },
    { name: "Riyan Parag", role: "AR", nat: "IND", category: "VOLATILE" },
    { name: "Shahrukh Khan", role: "BAT", nat: "IND", category: "VOLATILE" },
    { name: "Abdul Samad", role: "BAT", nat: "IND", category: "VOLATILE" },
    { name: "Shivam Mavi", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Kamlesh Nagarkoti", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Kartik Tyagi", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Chetan Sakariya", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Shahbaz Ahmed", role: "AR", nat: "IND", category: "CONSISTENT" },
    { name: "Yash Dayal", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Mukesh Choudhary", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Simarjeet Singh", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Tushar Deshpande", role: "BOWL", nat: "IND", category: "CONSISTENT" },
    { name: "Prabhsimran Singh", role: "WK", nat: "IND", category: "VOLATILE" },
    { name: "Jitesh Sharma", role: "WK", nat: "IND", category: "VOLATILE" },
    { name: "Ayush Badoni", role: "BAT", nat: "IND", category: "CONSISTENT" },
    { name: "Mohsin Khan", role: "BOWL", nat: "IND", category: "CONSISTENT" },
    { name: "Suyash Sharma", role: "BOWL", nat: "IND", category: "VOLATILE" },
    { name: "Nehal Wadhera", role: "BAT", nat: "IND", category: "VOLATILE" },
    { name: "Dhruv Jurel", role: "WK", nat: "IND", category: "CONSISTENT" },
    { name: "Yash Thakur", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Sai Sudharsan", role: "BAT", nat: "IND", category: "CONSISTENT" },
    { name: "Abhinav Manohar", role: "BAT", nat: "IND", category: "WEAK" },
    { name: "Rajvardhan Hangargekar", role: "AR", nat: "IND", category: "WEAK" },
    { name: "Prashant Chopra", role: "BAT", nat: "IND", category: "WEAK" },
    { name: "Anmolpreet Singh", role: "BAT", nat: "IND", category: "WEAK" },
    { name: "Ramandeep Singh", role: "AR", nat: "IND", category: "VOLATILE" },
    { name: "Akash Madhwal", role: "BOWL", nat: "IND", category: "VOLATILE" },
    { name: "Harshit Rana", role: "BOWL", nat: "IND", category: "VOLATILE" },
    { name: "Vaibhav Arora", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Suyash Prabhudessai", role: "BAT", nat: "IND", category: "WEAK" },
    { name: "Mahipal Lomror", role: "AR", nat: "IND", category: "WEAK" },
    { name: "Karn Sharma", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Siddarth Kaul", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Mayank Markande", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Shreyas Gopal", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Murugan Ashwin", role: "BOWL", nat: "IND", category: "WEAK" },
    { name: "Krishnappa Gowtham", role: "AR", nat: "IND", category: "WEAK" },
    { name: "Jalaj Saxena", role: "AR", nat: "IND", category: "WEAK" },
    { name: "Sarfaraz Khan", role: "BAT", nat: "IND", category: "WEAK" },
    { name: "Rajat Patidar", role: "BAT", nat: "IND", category: "CONSISTENT" },
    { name: "Devdutt Padikkal", role: "BAT", nat: "IND", category: "CONSISTENT" },
    { name: "KS Bharat", role: "WK", nat: "IND", category: "WEAK" },
    { name: "Wriddhiman Saha", role: "WK", nat: "IND", category: "CONSISTENT" },
    { name: "Jayant Yadav", role: "AR", nat: "IND", category: "WEAK" },
    { name: "Suresh Raina", role: "BAT", nat: "IND", category: "STAR" },
    { name: "Yuvraj Singh", role: "AR", nat: "IND", category: "STAR" },
    { name: "Gautam Gambhir", role: "BAT", nat: "IND", category: "STAR" },
    { name: "Virender Sehwag", role: "BAT", nat: "IND", category: "STAR" },
    { name: "Sachin Tendulkar", role: "BAT", nat: "IND", category: "STAR" },
    { name: "Harbhajan Singh", role: "BOWL", nat: "IND", category: "STAR" },
    { name: "Zaheer Khan", role: "BOWL", nat: "IND", category: "STAR" },
    { name: "Irfan Pathan", role: "AR", nat: "IND", category: "STAR" },
    { name: "Yusuf Pathan", role: "AR", nat: "IND", category: "STAR" },
    { name: "Ashish Nehra", role: "BOWL", nat: "IND", category: "STAR" },
    { name: "Robin Uthappa", role: "BAT", nat: "IND", category: "STAR" },
    { name: "Parthiv Patel", role: "WK", nat: "IND", category: "CONSISTENT" },
    { name: "Praveen Kumar", role: "BOWL", nat: "IND", category: "CONSISTENT" },

    // AUS
    { name: "David Warner", role: "BAT", nat: "AUS", category: "STAR" },
    { name: "Glenn Maxwell", role: "AR", nat: "AUS", category: "VOLATILE" },
    { name: "Mitchell Starc", role: "BOWL", nat: "AUS", category: "STAR" },
    { name: "Pat Cummins", role: "BOWL", nat: "AUS", category: "STAR" },
    { name: "Steve Smith", role: "BAT", nat: "AUS", category: "CONSISTENT" },
    { name: "Marcus Stoinis", role: "AR", nat: "AUS", category: "VOLATILE" },
    { name: "Cameron Green", role: "AR", nat: "AUS", category: "STAR" },
    { name: "Marnus Labuschagne", role: "BAT", nat: "AUS", category: "CONSISTENT" },
    { name: "Josh Hazlewood", role: "BOWL", nat: "AUS", category: "STAR" },
    { name: "Adam Zampa", role: "BOWL", nat: "AUS", category: "STAR" },
    { name: "Tim David", role: "BAT", nat: "AUS", category: "VOLATILE" },
    { name: "Matthew Wade", role: "WK", nat: "AUS", category: "WEAK" },
    { name: "Aaron Finch", role: "BAT", nat: "AUS", category: "WEAK" },
    { name: "Nathan Ellis", role: "BOWL", nat: "AUS", category: "CONSISTENT" },
    { name: "Daniel Sams", role: "AR", nat: "AUS", category: "WEAK" },
    { name: "Riley Meredith", role: "BOWL", nat: "AUS", category: "WEAK" },
    { name: "Jhye Richardson", role: "BOWL", nat: "AUS", category: "CONSISTENT" },
    { name: "Jason Behrendorff", role: "BOWL", nat: "AUS", category: "CONSISTENT" },
    { name: "Spencer Johnson", role: "BOWL", nat: "AUS", category: "VOLATILE" },
    { name: "Travis Head", role: "BAT", nat: "AUS", category: "STAR" },
    { name: "Mitchell Marsh", role: "AR", nat: "AUS", category: "STAR" },
    { name: "Ashton Agar", role: "AR", nat: "AUS", category: "CONSISTENT" },
    { name: "Josh Inglis", role: "WK", nat: "AUS", category: "VOLATILE" },
    { name: "Alex Carey", role: "WK", nat: "AUS", category: "CONSISTENT" },
    { name: "Kane Richardson", role: "BOWL", nat: "AUS", category: "WEAK" },
    { name: "Andrew Tye", role: "BOWL", nat: "AUS", category: "WEAK" },
    { name: "Chris Lynn", role: "BAT", nat: "AUS", category: "VOLATILE" },
    { name: "Sean Abbott", role: "AR", nat: "AUS", category: "WEAK" },

    // ENG
    { name: "Jos Buttler", role: "WK", nat: "ENG", category: "STAR" },
    { name: "Ben Stokes", role: "AR", nat: "ENG", category: "STAR" },
    { name: "Jonny Bairstow", role: "WK", nat: "ENG", category: "VOLATILE" },
    { name: "Liam Livingstone", role: "AR", nat: "ENG", category: "VOLATILE" },
    { name: "Sam Curran", role: "AR", nat: "ENG", category: "CONSISTENT" },
    { name: "Moeen Ali", role: "AR", nat: "ENG", category: "CONSISTENT" },
    { name: "Jofra Archer", role: "BOWL", nat: "ENG", category: "STAR" },
    { name: "Mark Wood", role: "BOWL", nat: "ENG", category: "STAR" },
    { name: "Adil Rashid", role: "BOWL", nat: "ENG", category: "STAR" },
    { name: "Reece Topley", role: "BOWL", nat: "ENG", category: "CONSISTENT" },
    { name: "Harry Brook", role: "BAT", nat: "ENG", category: "VOLATILE" },
    { name: "Will Jacks", role: "AR", nat: "ENG", category: "VOLATILE" },
    { name: "Phil Salt", role: "WK", nat: "ENG", category: "VOLATILE" },
    { name: "Jason Roy", role: "BAT", nat: "ENG", category: "VOLATILE" },
    { name: "David Willey", role: "AR", nat: "ENG", category: "WEAK" },
    { name: "Chris Jordan", role: "BOWL", nat: "ENG", category: "WEAK" },
    { name: "Dawid Malan", role: "BAT", nat: "ENG", category: "CONSISTENT" },
    { name: "Tymal Mills", role: "BOWL", nat: "ENG", category: "WEAK" },
    { name: "Luke Wood", role: "BOWL", nat: "ENG", category: "WEAK" },
    { name: "Joe Root", role: "BAT", nat: "ENG", category: "CONSISTENT" },
    { name: "Tom Curran", role: "AR", nat: "ENG", category: "WEAK" },
    { name: "Sam Billings", role: "WK", nat: "ENG", category: "WEAK" },
    { name: "Alex Hales", role: "BAT", nat: "ENG", category: "VOLATILE" },
    { name: "Eoin Morgan", role: "BAT", nat: "ENG", category: "STAR" },

    // NZ
    { name: "Kane Williamson", role: "BAT", nat: "NZ", category: "STAR" },
    { name: "Trent Boult", role: "BOWL", nat: "NZ", category: "STAR" },
    { name: "Tim Southee", role: "BOWL", nat: "NZ", category: "CONSISTENT" },
    { name: "Devon Conway", role: "WK", nat: "NZ", category: "STAR" },
    { name: "Daryl Mitchell", role: "AR", nat: "NZ", category: "CONSISTENT" },
    { name: "Lockie Ferguson", role: "BOWL", nat: "NZ", category: "VOLATILE" },
    { name: "Mitchell Santner", role: "AR", nat: "NZ", category: "CONSISTENT" },
    { name: "Glenn Phillips", role: "BAT", nat: "NZ", category: "VOLATILE" },
    { name: "Rachin Ravindra", role: "AR", nat: "NZ", category: "STAR" },
    { name: "Matt Henry", role: "BOWL", nat: "NZ", category: "CONSISTENT" },
    { name: "Finn Allen", role: "BAT", nat: "NZ", category: "VOLATILE" },
    { name: "Michael Bracewell", role: "AR", nat: "NZ", category: "WEAK" },
    { name: "Kyle Jamieson", role: "BOWL", nat: "NZ", category: "WEAK" },
    { name: "Adam Milne", role: "BOWL", nat: "NZ", category: "WEAK" },
    { name: "Jimmy Neesham", role: "AR", nat: "NZ", category: "VOLATILE" },
    { name: "Ish Sodhi", role: "BOWL", nat: "NZ", category: "WEAK" },
    { name: "Colin Munro", role: "BAT", nat: "NZ", category: "VOLATILE" },
    { name: "Martin Guptill", role: "BAT", nat: "NZ", category: "STAR" },
    { name: "Ross Taylor", role: "BAT", nat: "NZ", category: "STAR" },
    { name: "Corey Anderson", role: "AR", nat: "NZ", category: "VOLATILE" },
    { name: "Colin de Grandhomme", role: "AR", nat: "NZ", category: "WEAK" },

    // SA
    { name: "Quinton de Kock", role: "WK", nat: "SA", category: "STAR" },
    { name: "Kagiso Rabada", role: "BOWL", nat: "SA", category: "STAR" },
    { name: "Faf du Plessis", role: "BAT", nat: "SA", category: "STAR" },
    { name: "Aiden Markram", role: "BAT", nat: "SA", category: "CONSISTENT" },
    { name: "Heinrich Klaasen", role: "WK", nat: "SA", category: "STAR" },
    { name: "David Miller", role: "BAT", nat: "SA", category: "STAR" },
    { name: "Anrich Nortje", role: "BOWL", nat: "SA", category: "VOLATILE" },
    { name: "Lungi Ngidi", role: "BOWL", nat: "SA", category: "CONSISTENT" },
    { name: "Marco Jansen", role: "AR", nat: "SA", category: "CONSISTENT" },
    { name: "Tristan Stubbs", role: "WK", nat: "SA", category: "VOLATILE" },
    { name: "Rilee Rossouw", role: "BAT", nat: "SA", category: "VOLATILE" },
    { name: "Dewald Brevis", role: "BAT", nat: "SA", category: "VOLATILE" },
    { name: "Donovan Ferreira", role: "WK", nat: "SA", category: "WEAK" },
    { name: "Wayne Parnell", role: "BOWL", nat: "SA", category: "WEAK" },
    { name: "Keshav Maharaj", role: "BOWL", nat: "SA", category: "CONSISTENT" },
    { name: "Tabraiz Shamsi", role: "BOWL", nat: "SA", category: "WEAK" },
    { name: "Gerald Coetzee", role: "BOWL", nat: "SA", category: "VOLATILE" },
    { name: "Nandre Burger", role: "BOWL", nat: "SA", category: "VOLATILE" },
    { name: "AB de Villiers", role: "BAT", nat: "SA", category: "STAR" },
    { name: "Dale Steyn", role: "BOWL", nat: "SA", category: "STAR" },
    { name: "Imran Tahir", role: "BOWL", nat: "SA", category: "STAR" },

    // WI
    { name: "Andre Russell", role: "AR", nat: "WI", category: "STAR" },
    { name: "Sunil Narine", role: "AR", nat: "WI", category: "STAR" },
    { name: "Nicholas Pooran", role: "WK", nat: "WI", category: "STAR" },
    { name: "Rovman Powell", role: "BAT", nat: "WI", category: "VOLATILE" },
    { name: "Jason Holder", role: "AR", nat: "WI", category: "CONSISTENT" },
    { name: "Alzarri Joseph", role: "BOWL", nat: "WI", category: "VOLATILE" },
    { name: "Kyle Mayers", role: "AR", nat: "WI", category: "VOLATILE" },
    { name: "Romario Shepherd", role: "AR", nat: "WI", category: "VOLATILE" },
    { name: "Akeal Hosein", role: "BOWL", nat: "WI", category: "CONSISTENT" },
    { name: "Shimron Hetmyer", role: "BAT", nat: "WI", category: "VOLATILE" },
    { name: "Odean Smith", role: "AR", nat: "WI", category: "WEAK" },
    { name: "Obed McCoy", role: "BOWL", nat: "WI", category: "WEAK" },
    { name: "Shamar Joseph", role: "BOWL", nat: "WI", category: "VOLATILE" },
    { name: "Roston Chase", role: "AR", nat: "WI", category: "WEAK" },
    { name: "Chris Gayle", role: "BAT", nat: "WI", category: "STAR" },
    { name: "Kieron Pollard", role: "AR", nat: "WI", category: "STAR" },
    { name: "Dwayne Bravo", role: "AR", nat: "WI", category: "STAR" },

    // Rest of World (AFG, SL, BAN)
    { name: "Rashid Khan", role: "BOWL", nat: "AFG", category: "STAR" },
    { name: "Rahmanullah Gurbaz", role: "WK", nat: "AFG", category: "VOLATILE" },
    { name: "Naveen-ul-Haq", role: "BOWL", nat: "AFG", category: "CONSISTENT" },
    { name: "Mohammad Nabi", role: "AR", nat: "AFG", category: "CONSISTENT" },
    { name: "Fazalhaq Farooqi", role: "BOWL", nat: "AFG", category: "CONSISTENT" },
    { name: "Mujeeb Ur Rahman", role: "BOWL", nat: "AFG", category: "CONSISTENT" },
    { name: "Noor Ahmad", role: "BOWL", nat: "AFG", category: "STAR" },
    { name: "Azmatullah Omarzai", role: "AR", nat: "AFG", category: "CONSISTENT" },
    { name: "Gulbadin Naib", role: "AR", nat: "AFG", category: "VOLATILE" },
    { name: "Maheesh Theekshana", role: "BOWL", nat: "SL", category: "STAR" },
    { name: "Matheesha Pathirana", role: "BOWL", nat: "SL", category: "STAR" },
    { name: "Wanindu Hasaranga", role: "AR", nat: "SL", category: "STAR" },
    { name: "Dushmantha Chameera", role: "BOWL", nat: "SL", category: "WEAK" },
    { name: "Charith Asalanka", role: "BAT", nat: "SL", category: "WEAK" },
    { name: "Dasun Shanaka", role: "AR", nat: "SL", category: "WEAK" },
    { name: "Lasith Malinga", role: "BOWL", nat: "SL", category: "STAR" },
    { name: "Kumar Sangakkara", role: "WK", nat: "SL", category: "STAR" },
    { name: "Shakib Al Hasan", role: "AR", nat: "BAN", category: "STAR" },
    { name: "Mustafizur Rahman", role: "BOWL", nat: "BAN", category: "CONSISTENT" },
    { name: "Litton Das", role: "WK", nat: "BAN", category: "WEAK" },
    { name: "Taskin Ahmed", role: "BOWL", nat: "BAN", category: "WEAK" },
    { name: "Shoriful Islam", role: "BOWL", nat: "BAN", category: "WEAK" }
];

console.log("Total unique players generated:", realPlayers.length);

function getRealisticPrice(category) {
    if (category === 'STAR') {
        const slots = [17.0, 18.0, 19.5, 20.0, 22.0, 24.0, 25.5, 27.0];
        return slots[Math.floor(Math.random() * slots.length)].toFixed(2);
    } else if (category === 'VOLATILE') {
        const slots = [9.0, 10.0, 11.0, 12.0, 13.5, 15.0, 16.0];
        return slots[Math.floor(Math.random() * slots.length)].toFixed(2);
    } else if (category === 'CONSISTENT') {
        const slots = [7.0, 7.5, 8.0, 9.5, 10.0, 11.0, 12.0];
        return slots[Math.floor(Math.random() * slots.length)].toFixed(2);
    } else {
        const slots = [5.5, 6.0, 7.0, 7.5, 8.5];
        return slots[Math.floor(Math.random() * slots.length)].toFixed(2);
    }
}

// Remove duplicates if any
const uniquePlayers = [];
const seen = new Set();
for (const p of realPlayers) {
    if (!seen.has(p.name)) {
        seen.add(p.name);
        uniquePlayers.push(p);
    }
}

const sqlRows = uniquePlayers.map((p) => {
    const price = getRealisticPrice(p.category);
    return `  (gen_random_uuid(), '${p.name.replace(/'/g, "''")}', '${p.role}', '${p.category}', ${price}, '${p.nat}')`;
});

const sqlContent = `-- Auto-generated seed file with REAL players and realistic increments
INSERT INTO players (id, name, role, category, base_price, nationality) VALUES
${sqlRows.join(',\n')};
`;

fs.writeFileSync('supabase/seed.sql', sqlContent);
console.log('Successfully generated supabase/seed.sql with real players and realistic 0.5Cr prices!');
